### ISSUE TITLE
No effect

### ISSUE THREAD

**Issue by SpittingBull** [Wurmatron/Mining-Goggles#14]
Hi,
I am running Mining-Goggles v0.0.0.30 on Forge 1.12.2-forge1.12.2-14.23.5.2847 together with like 100 under mods.
Unfortunately your mod seems not to have any effect in my case. I can open both GUIs - one with the various colors, where I can edit text and turn something on or off.

In the other GUI that seems to be an inventory I can't place any items (I guess ingots or ores).

I even get the error message if the goggles are neither worn nor held.

In the log I could find warnings and errors related to your mod though:

```
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at net.minecraft.util.Util.runTask(Util.java:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:273)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
    at com.wurmatron.mininggoggles.common.network.container.InventoryGoggles.readFromNBT(InventoryGoggles.java:154)
    at com.wurmatron.mininggoggles.common.network.container.InventoryGoggles.<init>(InventoryGoggles.java:27)
    at com.wurmatron.mininggoggles.common.network.GuiHandler.getServerGuiElement(GuiHandler.java:27)
    at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:253)
    at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:88)
    at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550)
    at com.wurmatron.mininggoggles.common.network.packets.OpenGuiMessage.process(OpenGuiMessage.java:42)
    at com.wurmatron.mininggoggles.common.network.utils.CustomMessage.lambda$checkAndHandle$0(CustomMessage.java:20)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 5 more
```

and

`  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  Suspected Mods: Mining Goggles (mininggoggles)
 `

and

`[Client thread/WARN] [jei]: GUI did not draw the dark background layer behind itself, this may result in display issues: com.wurmatron.mininggoggles.client.gui.GuiGoggleModules`

It should be noted that I tried both OptiFine_1.12.2_HD_U_E3 and F4 - with and without shaders.

**Comment by Wurmatron** [comment]
Looks like the helmet you are using is missing some NBT data

**Comment by SpittingBull** [comment]
Just tell me if I can help debugging.

**Comment by Wurmatron** [comment]
Try grabbing the helmet out of the creative-tab,  and make sure it has some nbt with it (F3+H). From what I can see you are missing the modules tag

**Comment by SpittingBull** [comment]
Not sure if that's what it is - this is what I see just now in single player survival:

![grafik](https://user-images.githubusercontent.com/2861267/67971746-9e2c7980-fc0d-11e9-9e93-9b8801f1fe10.png)

Will try in creative as well.

**Comment by SpittingBull** [comment]
And in creative:

![grafik](https://user-images.githubusercontent.com/2861267/67972028-2ad73780-fc0e-11e9-84f2-482f676da5e3.png)

**Comment by SpittingBull** [comment]
There is one weird thing though:

If I click on the range 3 goggle in JEI it shows me the recipe for a range 4 (the one with the ender pearl). And that's what I crafted in survival. In creative I have both a range 3 and 4.

**Comment by Wurmatron** [comment]
That's just how JEI works you should be able to use the arrow to see the recipes for the higher tier'd ones.. So is it working or is this an actual bug?

**Comment by SpittingBull** [comment]
I justed wanted to show you a discrepancy in naming and recipies between Creative mode and JEI in reference to your suspicion in regards of NBT tags. What I meant was that in Creative I can take a tier 3 goggle, that is named range 3 whereas JEI shows the outcome of a tier 3 recipe as a tier 4 item. In survival I can not craft a tier 3 item at all. The tier 3 recipe leads to a tier 4 item.

In regards of item function I have to report that none of the items seem to have an effect even in Creative mode. As you can see in the screenshot below I am holding goggles and although there is lapis I don't see any visual representation. That is independent from wearing it as helmet or as baubles item. I tried every distance, I tried turning lapis on and off in the GUI, tried every angle but it does not matter.

![grafik](https://user-images.githubusercontent.com/2861267/67991096-5d962580-fc38-11e9-9ea5-8eb045124721.png)

**Comment by Wurmatron** [comment]
![NltoB6z](https://user-images.githubusercontent.com/5226577/67995792-b22ea600-fc22-11e9-86f8-cdf598ce3d1c.jpg)
"oreLapis"

Seems to be working
